Web/IRUN.WEB/Areas/Admin/Controllers/DistanceActivityController.cs
using Prj.Irun.BusinessLogic.Interfaces;
using Prj.Irun.BusinessLogic.Models;
using Prj.Irun.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IRUN.WEB.Areas.Admin.Controllers
{
    public class DistanceActivityController : BaseController
    {
        private readonly IcpDistanceActivityService _distanceActivityService;
        public DistanceActivityController(IcpDistanceActivityService distanceActivityService)
        {
            _distanceActivityService = distanceActivityService;
        }

        // GET: Admin/DistanceActivity
        public ActionResult Index(int? Page)
        {
            try
            {
                var model = new DistanceActivity_DataModel();
                model.PageIndex = Protector.Int(Page, 1);
                model.PageSize = 50;

                var list = _distanceActivityService.GetAll(model);
                long lCount = list.data.Count;
                #region Paging
                if (lCount > 0)
                {
                    if (PagingHelper.GetUrl(this.Request.Url.PathAndQuery) == this.Request.Url.AbsolutePath)
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(this.Request.Url.AbsolutePath, lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 1);
                    }
                    else
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(PagingHelper.GetUrl(this.Request.Url.PathAndQuery), lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 2);
                    }
                }
                #endregion
                ViewBag.Count = list.data.Count;
                ViewBag.listData = list.data.List;
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(int? Page, string userID)
        {
            try
            {
                var model = new DistanceActivity_DataModel();
                model.PageIndex = Protector.Int(Page, 1);
                model.PageSize = 50;

                var list = _distanceActivityService.SearchByUserID(model, userID);
                long lCount = list.data.Count;
                #region Paging
                if (lCount > 0)
                {
                    if (PagingHelper.GetUrl(this.Request.Url.PathAndQuery) == this.Request.Url.AbsolutePath)
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(this.Request.Url.AbsolutePath, lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 1);
                    }
                    else
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(PagingHelper.GetUrl(this.Request.Url.PathAndQuery), lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 2);
                    }
                }
                #endregion
                ViewBag.Count = list.data.Count;
                ViewBag.listData = list.data.List;
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View();
        }

        public JsonResult Delete(int id)
        {
            string msg = "";
            try
            {
                var result = _distanceActivityService.Delete(Protector.Int(id));
                if (result.success.Equals(true))
                {
                    msg = "OK";
                }
                else
                {
                    msg = "Oop! Something wrong, please try again...";
                }
            }
            catch (Exception ex)
            {
                msg = ex.ToString();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(int id)
        {
            try
            {
                var msg = _distanceActivityService.GetByID(id);

                return View(msg.data);
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Update(FormCollection fc, DistanceActivityModel model)
        {
            try
            {
                var msg = _distanceActivityService.Updated(model);

                if (msg.success.Equals(true))
                {
                    return RedirectToAction("/Index");
                }
                else
                {
                    ViewBag.message = msg.message;
                }

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }


        public ActionResult Add()
        {
            try
            {

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Add(FormCollection fc, DistanceActivityModel model)
        {
            try
            {
                var data_response = _distanceActivityService.Add(model);

                return RedirectToAction("/Index");
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }
    }
}

Web/IRUN.WEB/Areas/Admin/Views/DistanceActivity/Add.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@model DistanceActivityModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <h1>
        Add DistanceActivity
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">Add DistanceActivity</li>
    </ol>
</section>

<section class="content">

    @using (Html.BeginForm("Add", "DistanceActivity", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
    {
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for=""></label>
                                @Html.Raw(ViewBag.message)
                            </div>
                            <div class="form-group">
                                <label>UserID</label>
                                @Html.TextBoxFor(model => model.UserID, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.UserID)
                            </div>
                            <div class="form-group">
                                <label>Distance</label>
                                @Html.TextBoxFor(model => model.Distance, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Distance)
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-warning">Add</button> &nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>

        </div>
    }
</section>

Web/IRUN.WEB/Areas/Admin/Views/DistanceActivity/Index.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@model DistanceActivityModel
@{
    List<DistanceActivityModel> listData = ViewBag.listData;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <h1>DistanceActivity</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">DistanceActivity</li>
    </ol>
</section>
<section class="content">
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Username:</label>
                                    @Html.TextBoxFor(model => model.UserID, new { @class = "form-control", maxlength = 10 })
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label></label>
                                    <input type="submit" id="btFilter" style="margin-top:24px;" name="submit" class="btn btn-primary filterable" value="Search" /> &nbsp;
                                    <input type="button" id="btnAdd" style="margin-top:24px;" class="btn btn-warning" value="Add" /> &nbsp;
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label></label>

                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="box-body">

                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr class="filters">
                                        <th class="col-xs-1  text-center">STT</th>
                                        <th class="col-xs-2 text-center">UserID</th>
                                        <th class="col-xs-1 text-center">Distance</th>
                                        <th class="col-xs-2 text-center">ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{var countSTT = 0;}
                                    @foreach (var item in listData)
                                    {
                                        countSTT++;
                                        <tr>
                                            <td>@countSTT</td>
                                            <td><a href="@Url.Action("Update", new { id = @item.Id })">@item.UserID</a></td>
                                            <td align="center" class="center">@item.Distance</td>                                            
                                            <td align="center" width="100px">
                                                <a class="fa fa-fw fa-edit" href="/Admin/DistanceActivity/Update/@item.Id" title="Details"></a>
                                                <a class="fa fa-trash-o" href="#" onclick="DeleteRow('/Admin/DistanceActivity/Delete?ID=' + @item.Id);" title="Delete"></a>
                                            </td>
                                        </tr>
                                                }
                                </tbody>
                            </table>
                            <div class="box-footer clearfix">
                                @Html.Raw(ViewData["Page"])
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div>
                                                }
</section>

<script type="text/javascript">
    $('#btnAdd').click(function () {
        window.location.href = "/Admin/DistanceActivity/Add";
    });

    function DeleteRow(urlRequest) {
        DialogConfirm('Are you sure to delete ?', 1, function () {
            DeleteRowAjax("GET", urlRequest, "/Admin/DistanceActivity/Index");
        });
    }
</script>

Web/IRUN.WEB/Areas/Admin/Views/DistanceActivity/Update.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@model DistanceActivityModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <h1>
        Update DistanceActivity
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">Update DistanceActivity</li>
    </ol>
</section>

<section class="content">

    @using (Html.BeginForm("Update", "DistanceActivity", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
    {
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for=""></label>
                                @Html.Raw(ViewBag.message)
                            </div>
                            <div class="form-group">
                                <label>UserID</label>
                                @Html.TextBoxFor(model => model.UserID, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.UserID)
                            </div>
                            <div class="form-group">
                                <label>Distance</label>
                                @Html.TextBoxFor(model => model.Distance, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Distance)
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-warning">Update</button> &nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>

        </div>
    }
</section>