Web/IRUN.WEB/Areas/Admin/Controllers/APIParameterController.cs
using Prj.Irun.BusinessLogic.Interfaces;
using Prj.Irun.BusinessLogic.Models;
using Prj.Irun.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IRUN.WEB.Areas.Admin.Controllers
{
    public class APIParameterController : BaseController
    {
        private readonly IcpAPIParameterService _apiParameterService;
        public APIParameterController(IcpAPIParameterService APIParameterService)
        {
            _apiParameterService = APIParameterService;
        }

        public ActionResult Index(int? Page)
        {
            try
            {
                var model = new APIParameter_DataModel();
                model.PageIndex = Protector.Int(Page, 1);
                model.PageSize = 50;

                var list = _apiParameterService.GetAll(model);
                long lCount = list.data.Count;
                #region Paging
                if (lCount > 0)
                {
                    if (PagingHelper.GetUrl(this.Request.Url.PathAndQuery) == this.Request.Url.AbsolutePath)
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(this.Request.Url.AbsolutePath, lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 1);
                    }
                    else
                    {
                        ViewData["Page"] = PagingHelper.PagingAdmin(PagingHelper.GetUrl(this.Request.Url.PathAndQuery), lCount, ProtectorHelper.Int(model.PageSize), ProtectorHelper.Int(model.PageIndex), 2);
                    }
                }
                #endregion
                ViewBag.Count = list.data.Count;
                ViewBag.listData = list.data.List;
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View();
        }

        public JsonResult Delete(string CodeID)
        {
            string msg = "";
            try
            {
                var result = _apiParameterService.Delete(CodeID);
                if (result.success.Equals(true))
                {
                    msg = "OK";
                }
                else
                {
                    msg = "Oop! Something wrong, please try again...";
                }
            }
            catch (Exception ex)
            {
                msg = ex.ToString();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(string CodeID)
        {
            try
            {
                var msg = _apiParameterService.GetByID(CodeID);

                return View(msg.data);
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Update(FormCollection fc, APIParameterModel model)
        {
            try
            {
                var msg = _apiParameterService.Updated(model);

                if (msg.success.Equals(true))
                {
                    return RedirectToAction("/Index");
                }
                else
                {
                    ViewBag.message = msg.message;
                }

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }


        public ActionResult Add()
        {
            try
            {

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Add(FormCollection fc, APIParameterModel model)
        {
            try
            {
                model.IsDeleted = false;
                model.CodeID = Globals.RandomCode(5);
                var data_response = _apiParameterService.Add(model);

                return RedirectToAction("/Index");
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View();
        }
    }
}

Web/IRUN.WEB/Areas/Admin/Views/APIParameter/Add.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@model APIParameterModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <h1>
        Add APIParameter
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">Add APIParameter</li>
    </ol>
</section>

<section class="content">

    @using (Html.BeginForm("Add", "APIParameter", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
    {
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for=""></label>
                                @Html.Raw(ViewBag.message)
                            </div>
                            <div class="form-group">
                                <label>Name</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                @Html.TextBoxFor(model => model.Description, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Description)
                            </div>
                            <div class="form-group">
                                <label>Ratio</label>
                                @Html.TextBoxFor(model => model.Ratio, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Ratio)
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-warning">Add</button> &nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>

        </div>
    }
</section>

Web/IRUN.WEB/Areas/Admin/Views/APIParameter/Index.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@{
    List<APIParameterModel> listData = ViewBag.listData;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <h1>APIParameter</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">APIParameter</li>
    </ol>
</section>
<section class="content">
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label></label>
                                    <input type="button" id="btnAdd" style="margin-top:24px;" class="btn btn-warning" value="Add" /> &nbsp;
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="box-body">

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th class="col-xs-1 text-center">STT</th>
                                    <th class="col-xs-1 text-center">Name</th>
                                    <th class="col-xs-1 text-center">CodeID</th>
                                    <th class="col-xs-1 text-center">Description</th>
                                    <th class="col-xs-1 text-center">Ratio</th>
                                    <th class="col-xs-1 text-center">ACTION</th>
                                </tr>
                                @{
                                    var countSTT = 0;
                                    if (listData != null)
                                    {
                                        foreach (var item in listData)
                                        {
                                            countSTT++;
                                <tr>
                                    <td>@countSTT</td>
                                    <td><a href="@Url.Action("Update", new { CodeID = @item.CodeID })">@item.Name</a></td>
                                    <td align="center" class="center">@item.CodeID</td>
                                    <td align="center" class="center">@item.Description</td>
                                    <td align="center" class="center">@item.Ratio</td>
                                    <td align="center" width="100px">
                                        <a class="fa fa-fw fa-edit" href="/Admin/APIParameter/Update?CodeID=@item.CodeID" title="Details"></a>
                                        <a class="fa fa-trash-o" href="#" onclick="DeleteRow('/Admin/APIParameter/Delete?CodeID=@item.CodeID');" title="Delete"></a>
                                    </td>
                                </tr>
                                        }
                                    }
                                }
                            </table>

                            <div class="box-footer clearfix">
                                @Html.Raw(ViewData["Page"])
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div>
    }
</section>

<script type="text/javascript">
    $('#btnAdd').click(function () {
        window.location.href = "/Admin/APIParameter/Add";
    });

    function DeleteRow(urlRequest) {


        DialogConfirm('Are you sure to delete ?', 1, function () {
            DeleteRowAjax("GET", urlRequest, "/Admin/APIParameter/Index");
        });
    }

</script>

Web/IRUN.WEB/Areas/Admin/Views/APIParameter/Update.cshtml
@using Prj.Irun.Utilities;
@using Prj.Irun.BusinessLogic.Models;
@model APIParameterModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <h1>
        Update APIParameter
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i>DashBoard</a></li>
        <li class="active">Update APIParameter</li>
    </ol>
</section>

<section class="content">

    @using (Html.BeginForm("Update", "APIParameter", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
    {
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <!-- form start -->

                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for=""></label>
                                @Html.Raw(ViewBag.message)
                            </div>
                            <div class="form-group">
                                <label>Name</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                @Html.TextBoxFor(model => model.Description, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Description)
                            </div>
                            <div class="form-group">
                                <label>Ratio</label>
                                @Html.TextBoxFor(model => model.Ratio, new { @class = "form-control", maxlength = 150, placeholder = "" })
                                @Html.ValidationMessageFor(model => model.Ratio)
                            </div>
                            <div class="form-group">
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.CodeID)
                                @Html.HiddenFor(model => model.IsDeleted)
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-warning">Update</button> &nbsp;&nbsp;
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>

        </div>
    }
</section>